#ifndef _MAIN_H
#define _MAIN_H

#include "led.h"
#include "led8.h"
#include "beep.h"
#include "delay.h"
#include "pwm.h"
#include "run.h"
#include "rundriver.h"
#include "pid.h"
#include "includes.h"
#include "can1.h"
#include "visual_scope.h"
#include "stm32f4xx.h"
#include "stdarg.h"
#include "stdio.h"
#include "ili9320_api.h"
#include "ili9320.h"
#include "string.h"
#include "usart1.h"
#include "key.h"
#include "can2.h"
#include "usart2.h"
#include "lcd.h"
#include "motor.h"
#include "flash.h"
#include "tim.h"
#include "MyMath.h"
#include "exti.h"

#endif
